import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Render the application's root HTML and body wrapper.
 *
 * Renders an <html lang="en"> element containing a <body> that applies the Geist
 * sans and mono font CSS variables and antialiasing, and mounts the provided
 * children inside the body.
 *
 * @param children - The page or app content to render inside the body
 * @returns A JSX element containing the root `<html>` and `<body>` wrapper with fonts applied
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}